### ISSUE TITLE
Docpie skips description with -h

### ISSUE THREAD

**Issue by thorstenkampe** [TylerTemp/docpie#10]
Given below docstring, `docpie` does not print the description (just usage and options). In comparison, `docopt` prints the full docstring
```
"""
`SCRIPT` DESCRIPTION

Usage:
 SCRIPT [options]

Options:
 -h, --help   show help
"""
```

**Comment by TylerTemp** [comment]
fixed in `0.4.0` and released. Feel free to reopen if it still happens
