### ISSUE TITLE
Repeatable arguments initialized as empty list when setting "appearedonly=True"

### ISSUE THREAD

**Issue by Branhuang** [TylerTemp/docpie#12]
Hey man. I was using your package but it does not work as expected. My `__doc__`:

```
Usage: 
    create [--vbf_version=VBFVERSION]
           [--description=DESCRIPTION]...
           [--parameter_settings=(PARAMETER PARAMETERVALUE)]           
           [([--vbt_sort | --vbt_last] --sign=ADDRESS)]
```

But when I give argv as: 

```
--sign=0x00 --vbt_last
```

it give the result:

```
{'--': False,
 '--description': [],
 '--sign': '0x00',
 '--vbt_last': True}
```

Why the option '--description' is '[]' in the resulted dictionary when I choose "appearedonly=True"?
From my understanding, it shouldn't appear in the dict because I haven't input it from argv from the command line, or?

`docpie` version: 0.3.6 / Sat Jul  1 01:54:16 2017

Here is the [online demo](http://docpie.comes.today/try/?doc=Usage%3A+%0D%0A++++create+%5B--vbf_version%3DVBFVERSION%5D%0D%0A+++++++++++%5B--description%3DDESCRIPTION%5D...%0D%0A+++++++++++%5B--parameter_settings%3D%28PARAMETER+PARAMETERVALUE%29%5D+++++++++++%0D%0A+++++++++++%5B%28%5B--vbt_sort+%7C+--vbt_last%5D+--sign%3DADDRESS%29%5D&argv=--sign%3D0x00+--vbt_last&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on&appearedonly=on)

**Comment by TylerTemp** [comment]
Feel free to reopen this issue if it still kicks in :)

**Comment by Branhuang** [comment]
Just tried it and it works now. Many thanks!
