### ISSUE TITLE
502 Bad Gateway 

### ISSUE THREAD

**Issue by thechief389** [TylerTemp/docpie#15]
The website, docpie.comes.today, doesn’t work anymore. (Bad gateway)

Can this be fixed?

**Comment by TylerTemp** [comment]
Hi, it's down already and, gonna move somewhere else. Thanks for reporting, will be fixed soon

**Comment by TylerTemp** [comment]
temporarily moved to <http://docpie.notexists.top/try/>, thanks for reporting, will fix the old domain later

**Comment by TylerTemp** [comment]
Fixed: <https://docpie.comes.today/try>
