### ISSUE TITLE
Docpie ignores the relationships specified as options

### ISSUE THREAD

**Issue by kjellolsson** [TylerTemp/docpie#17]
Hey man. I was using your package but it does not work as expected. My `__doc__`:

```
Usage: xx --node <url> --image <os_image> [--kick <kicker>]
options:
-n, --node <url>
-i, --image <os_image>
-k, --kick <kicker>
```
When I specify: 
--node node_url --image pu_image
things work fine.

But when I give argv as: 
```
--image pu_image --node node_url
```

it give the result:

```
{'--': False,
 '--image': True,
 '--kick': False,
 '--node': True,
 '<kicker>': None,
 '<os_image>': 'node_url',
 '<url>': 'pu_image'}
```

WTF? <os_image> is now the url and <url> is the image.

`docpie` version: 0.4.1 / Sun Jan 28 21:04:33 2018

Here is the [online demo](http://docpie.comes.today/try/?doc=Usage%3A+xx+--node+%3Curl%3E+--image+%3Cos_image%3E+%5B--kick+%3Ckicker%3E%5D%0D%0Aoptions%3A%0D%0A-n%2C+--node+%3Curl%3E%0D%0A-i%2C+--image+%3Cos_image%3E%0D%0A-k%2C+--kick+%3Ckicker%3E&argv=--image+pu_image+--node+node_url&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on)

**Comment by TylerTemp** [comment]
hi,

`Usage` section and `Option` section requires at least one blank line to separate, which is different from `docopt`

```python
# pie.py
"""
Usage: xx --node <url> --image <os_image> [--kick <kicker>]

options:
-n, --node <url>
-i, --image <os_image>
-k, --kick <kicker>
"""

from docpie import docpie

args = docpie(__doc__)
print(args)
```

result:

```
$ python pie.py --image pu_image --node node_url
{'--': False,
 '--image': 'pu_image',
 '--kick': None,
 '--node': 'node_url',
 '-i': 'pu_image',
 '-k': None,
 '-n': 'node_url'}
```

Here is the [online demo](http://docpie.comes.today/try/?doc=Usage%3A+xx+--node+%3Curl%3E+--image+%3Cos_image%3E+%5B--kick+%3Ckicker%3E%5D%0D%0A%0D%0Aoptions%3A%0D%0A-n%2C+--node+%3Curl%3E%0D%0A-i%2C+--image+%3Cos_image%3E%0D%0A-k%2C+--kick+%3Ckicker%3E&argv=--image+pu_image+--node+node_url&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on)

**Comment by TylerTemp** [comment]
Close because of inactive.
