### ISSUE TITLE
Simple test doesn't work?

### ISSUE THREAD

**Issue by Branhuang** [TylerTemp/docpie#8]
Hey man. I was using your package but it does not work as expected. My `__doc__`:

```
naval_fate --ship shipname
```

But when I give argv as: 

```
naval_fate --ship ship1
```

it give the result:

```
Can't convert 'NoneType' object to str implicitly
```

WTF? What the hell was going on?

`docpie` version: 0.3.6 / Sat Jul  1 01:54:16 2017

Here is the [online demo](http://docpie.comes.today/try/?doc=naval_fate+--ship+shipname&argv=naval_fate+--ship+ship1&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on)

**Comment by TylerTemp** [comment]
Hi,

1.  `Usage:` header is required
2.  on the online demo you do not need to pass the program's name to the command line, cuz it's already written before the input area
3.  `Argument` should always be uppercase or surrounded by `<` and `>`

Plz see [online demo 1](http://docpie.comes.today/try/?doc=Usage%3A+naval_fate+--ship+%3Cshipname%3E&argv=--ship+ship1&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on&name=naval_fate) and [online demo 2](http://docpie.comes.today/try/?doc=Usage%3A+naval_fate+--ship+SHIPNAME&argv=--ship+ship1&run=on&help=on&stdopt=on&attachopt=on&attachvalue=on&auto2dashes=on&name=naval_fate)

**Comment by TylerTemp** [comment]
Feel free to reopen it if you still hit this problem
